Math

In [6]:
#Funcion math
import math
#Me regresa el entero más próximo (math.ceil)

a = 1.3

math.ceil(a)

2

In [ ]:
print(math)

In [5]:
print(math.isinf(56))

False


Random

In [8]:
#Primero se importa, y sirve para obtener un numero aleatorio y realizar análisis estadístico, y reaizar encriptaciones.
import random
random.seed(1)
print(random.random())

0.13436424411240122


In [9]:
import random
mylist=["manzana", "pera","chayote"]
random.choice(mylist)

'manzana'

In [10]:
#Pueden salir los mismos parámetros repetidos
import random
mylist=["manzana", "pera","chayote", "berengena", "papaya"]
random.choices(mylist, k=3)

['pera', 'chayote', 'chayote']

In [11]:
# "sample" no permite repeticiones
random.sample(mylist, k=3)

['berengena', 'pera', 'manzana']

Numpy

In [12]:
#Es para hacer cálculos numéricos, se importa:
import numpy as np #Es el alias de referencia cuando lo citemos abajo.
#Arreglos:
arr = np.array([4,5,2,5,7,3])
print(arr)
print(type(arr))

[4 5 2 5 7 3]
<class 'numpy.ndarray'>


In [16]:
#Las operaciones aqui son entrada por entrada (vectorizadas)
arr*3

array([12, 15,  6, 15, 21,  9])

In [17]:
#Se pueden ocupar tuplas
arr1 = np.array((1,2,3,4,5,6))
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [22]:
#1 dimensión:
arr2=([[[2,4,6],[5,2,7]], [[65,21,45]]])