In [ ]:
#Arreglos con solo un paréntesis es un arreglo 0 dimensional. Un paréntesis y un corchete 1 dimensional,
#dos bloquecitos de corchetes encerrados en otro corchete y luego un paréntesis 2 dimensional

In [2]:
import numpy as np
arr = np.array([[1,2,4],[4,2,6]]) #Cada bloque de corchetes es una fila
print(arr)

[[1 2 4]
 [4 2 6]]


In [4]:
#Cuando se hacen bloques mas grandes con matrioces cada uno, primero se imprimen los cortes en el cubo y luego las dimensiones de las caras del cubo
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(d.ndim,d.shape)

3 (2, 2, 3)


In [7]:
a = np.array([1,2,3,4,5])
print(a.ndim,a.shape)
#Los arreglos son hijos de las listas

1 (5,)


In [8]:
print(a[0])

1


In [9]:
print(a[1:5])

[2 3 4 5]


In [10]:
print(a[2:]) #Para imprimir hasta el final

[3 4 5]


In [11]:
#Para empezar desde el principio
print(a[:3])

[1 2 3]


In [12]:
#Para imprimir todo:
print(a[:])

[1 2 3 4 5]


In [13]:
#Para imprimir en una sucesión:
print(a[1:4:2]) #El último dígito es para ver de a cuanto van los saltitos

[2 4]


Arreglos bidimencionales

In [15]:
B = np.array([[1,2,3], [4,5,6]]) #Aqui los elementos son los bloquecitos:
print(B[0])

[1 2 3]


In [17]:
print(B[1][1]) #Agarra, del bloque 1 al elemento 1

5


In [18]:
print(B[:])

[[1 2 3]
 [4 5 6]]


In [19]:
print(B[:,1]) #De todos los arreglos se agarra el elemento 1

[2 5]


In [20]:
print(B[:][1]) #Me tomo los dos arreglos y agarro el número 1
#Siempre que se seleccionen rebanadas se usa la coma

[4 5 6]


In [21]:
#Seleccionas 1,2 y 4,5
print(B[:,0:2])

[[1 2]
 [4 5]]


In [22]:
print(B[:,::2])

[[1 3]
 [4 6]]


In [23]:
print(B[0,0:2]) #Lo que va después de los puntitos es para delimitar, y luego el rango de donde se va a agarrar

[1 2]


In [31]:
m=np.array([1,2,3,4,5])
m<4

array([ True,  True,  True, False, False])

In [32]:
m=np.array([1,2,3,4,5])
m%2 == 0 #Para dividir entre 2 y ver cual tiene residuo 0

array([False,  True, False,  True, False])

In [34]:
m=np.array([1,2,3,4,5])
m[m%2 == 0]  #Para darme los elementos que cumplan la condición. Máscaras buleanas

array([2, 4])

In [33]:
m[m>=4]

array([4, 5])

In [35]:
#Para hacerlo con el índice
MITres=m[np.where(m>=3)]
MITres

array([3, 4, 5])

In [36]:
(m<3) | (m>3)  #Unión, en lugar de "or"

array([ True,  True, False,  True,  True])

In [37]:
(m<3) & (m>3) #en lugar de "and". Intersección

array([False, False, False, False, False])

Factorial

In [47]:
#Factorial iterativo, hecho en clase:
def factorial(n):
  if type(n)==int:
    fact=1 #Es un contador
    for i in range(n):
      fact=fact*(i+1) #Le sumamos 1 porque empieza en 0, y así hace que termine en el número que pedimos

    return fact
  else:
    print("Inválido")
factorial("J")
#Para comentar el código podemos usas "DeepSeek"

Inválido
